name: test
on:
  - push
  - pull_request
jobs:
  test:
    name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
          - 18
          - 16
          - 14
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v3
      - if: contains(matrix.os, 'ubuntu')
        run: sudo apt-get install nasm libpng-dev
      - if: contains(matrix.os, 'macos')
        run: brew install automake nasm zlib libpng
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
